"""add column original  to UserEditsModel

Revision ID: 76df714ef894
Revises: 002dde892baa
Create Date: 2025-05-27 13:19:03.758628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76df714ef894"
down_revision: Union[str, None] = "002dde892baa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_edits", sa.Column("original_text", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_edits", "original_text")
    # ### end Alembic commands ###
