"""remove columns

Revision ID: af6d67213e8f
Revises: 76df714ef894
Create Date: 2025-05-27 14:17:10.918531

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af6d67213e8f"
down_revision: Union[str, None] = "76df714ef894"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_edits_dictation_id"), table_name="user_edits")
    op.drop_constraint(
        op.f("user_edits_dictation_id_fkey"), "user_edits", type_="foreignkey"
    )
    op.drop_column("user_edits", "dictation_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_edits",
        sa.Column("dictation_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("user_edits_dictation_id_fkey"),
        "user_edits",
        "dictations",
        ["dictation_id"],
        ["id"],
    )
    op.create_index(
        op.f("ix_user_edits_dictation_id"), "user_edits", ["dictation_id"], unique=False
    )
    # ### end Alembic commands ###
